async function enviarScript() {
    const messages = [
        "Firmeza total, mais um ano se passando",
        "Graças a Deus a gente 'tá com saúde aí, 'morô?",
        "Muita coletividade na quebrada, dinheiro no bolso",
        "Sem miséria, e é nóis",
        "Vamos brindar o dia de hoje",
        "Que o amanhã só pertence a Deus, a vida é loka",
        "'Xô falá pro'cê",
        "Tudo, tudo, tudo vai, tudo é fase irmão",
        "Logo mais vamo arrebentar no mundão",
        "De cordão de elite, 18 quilates",
        "Poê no pulso, logo um Breitling",
        "Que tal? 'Tá bom?",
        "De lupa Bausch & Lomb, bombeta branco e vinho",
        "Champagne para o ar, que é pra abrir nossos caminhos",
        "Pobre é o diabo, eu odeio a ostentação",
        "Pode rir, ri, mais não desacredita não",
        "É só questão de tempo, o fim do sofrimento",
        "Um brinde pros guerreiro, zé povinho eu lamento",
        "Vermes que só faz peso na Terra",
        "Tira o zóio",
        "Tira o zóio, vê se me erra",
        "Eu durmo pronto pra guerra",
        "E eu não era assim, eu tenho ódio",
        "E sei o que é mau pra mim",
        "Fazer o que se é assim",
        "Vida loka cabulosa",
        "O cheiro é de pólvora",
        "E eu prefiro rosas",
        "E eu que, e eu que",
        "Sempre quis com um lugar, Gramado e limpo, assim, verde como o mar",
        "Cercas brancas, uma seringueira com balança",
        "Disbicando pipa, cercado de criança",
        "How, how Brown",
        "Acorda sangue bom, Aqui é Capão Redondo, tru",
        "Não é pokemón",
        "Zona sul é o invés, é stress concentrado",
        "Um coração ferido, por metro quadrado",
        "Quanto, mais tempo eu vou resistir",
        "Pior que eu já vi meu lado bom na U.T.I.",
        "Meu anjo do perdão foi bom, Mas 'tá fraco",
        "Culpa dos imundo, do espírito opaco",
        "Eu queria ter, pra testar e ver",
        "Um malote, com glória, fama",
        "Embrulhado em pacote",
        "Se é isso que 'cês quer",
        "Vem pegar",
        "Jogar num rio de merda e ver vários pular",
        "Dinheiro é foda",
        "Na mão de favelado, é mó' guela",
        "Na crise, vários pedra-noventa esfarela",
        "Eu vou jogar pra ganhar",
        "O meu money, vai e vem",
        "Porém, quem tem, tem",
        "Não cresço o zóio em ninguém",
        "O que tiver que ser",
        "Será meu",
        "'Tá escrito nas estrelas",
        "Vai reclamar com Deus",
        "Imagina nóis de Audi",
        "Ou de Citroen",
        "Indo aqui, indo ali",
        "Só pam",
        "De vai e vem",
        "No Capão, no Apurá, vô colar",
        "Na pedreira do São Bento",
        "Na fundão, no pião",
        "Sexta-feira",
        "De teto solar",
        "O luar representa",
        "Ouvindo Cassiano, há",
        "Os gambé não guenta",
        "Mas se não der, nêgo",
        "O que é que tem",
        "O importante é nós aqui",
        "Junto ano que vem",
        "O caminho",
        "Da felicidade ainda existe",
        "É uma trilha estreita",
        "Em meio à selva triste",
        "Quanto 'cê paga",
        "Pra ver sua mãe agora",
        "E nunca mais ver seu pivete ir embora",
        "Dá a casa, dá o carro",
        "Uma Glock, e uma FAL",
        "Sobe cego de joelho",
        "Mil e cem degraus",
        "Crente é mil graus",
        "O que o guerreiro diz",
        "O promotor é só um homem",
        "Deus é o juiz",
        "Enquanto Zé Povinho",
        "Apedrejava a cruz",
        "E o canalha, fardado",
        "Cuspiu em Jesus",
        "Oh, aos 45 do segundo arrependido",
        "Salvo e perdoado",
        "É Dimas o bandido",
        "É loko o bagulho",
        "Arrepia na hora",
        "Oh, Dimas, primeiro vida loka da história",
        "Eu digo: 'Glória, glória'",
        "Sei que Deus 'tá aqui",
        "E só quem é",
        "Só quem é vai sentir",
        "E meus guerreiro de fé",
        "Quero ouvir, quero ouvir",
        "E meus guerreiro de fé",
        "Quero ouvir, irmão",
        "Programado pra morrer nós é",
        "Certo é certo é crer no que der, firmeza?",
        "Não é questão de luxo",
        "Não é questão de cor",
        "É questão que fartura",
        "Alegra o sofredor",
        "Não é questão de preza, nêgo",
        "A ideia é essa",
        "Miséria traz tristeza e vice-versa",
        "Inconscientemente vem na minha mente inteira",
        "Na loja de tênis o olhar do parceiro feliz",
        "De poder comprar o azul, o vermelho",
        "O balcão, o espelho",
        "O estoque, a modelo, não importa",
        "Dinheiro é puta e abre as portas",
        "Dos castelos de areia que quiser",
        "Preto e dinheiro, são palavras rivais",
        "E então mostra pra esses cu",
        "Como é que faz",
        "O seu enterro foi dramático",
        "Como um blues antigo",
        "Mas de estilo, me perdoe, de bandido",
        "Tempo pra pensar, quer parar",
        "Que 'cê quer?",
        "Viver pouco como um rei ou muito, como um Zé?",
        "Às vezes eu acho que todo preto como eu",
        "Só quer um terreno no mato, só seu",
        "Sem luxo, descalço, nadar num riacho",
        "Sem fome, pegando as frutas no cacho",
        "Aí truta, é o que eu acho",
        "Quero também, mas em São Paulo",
        "Deus é uma nota de cem",
        "Vida Loka!",
        "Porque o guerreiro de fé nunca gela",
        "Não agrada o injusto, e não amarela",
        "O Rei dos reis, foi traído, e sangrou nessa terra",
        "Mas morrer como um homem é o prêmio da guerra",
        "Mas ó, conforme for, se precisa, afoga no próprio sangue, assim será",
        "Nosso espírito é imortal, sangue do meu sangue",
        "Entre o corte da espada e o perfume da rosa",
        "Sem menção honrosa, sem massagem.",
        "A vida é loka, nêgo",
        "E nela eu tô de passagem",
        "A Dimas, o primeiro",
        "Saúde guerreiro!",
        "Dimas, Dimas, Dimas"
    ];
    const main = document.querySelector("#main");
    const textarea = main.querySelector(`div[contenteditable="true"]`);

    if (!textarea) throw new Error("Não há uma conversa aberta");

    for (const message of messages) {
        textarea.focus();
        document.execCommand('insertText', false, message);
        textarea.dispatchEvent(new Event('change', { bubbles: true }));

        setTimeout(() => {
            (main.querySelector(`[data-testid="send"]`) || main.querySelector(`[data-icon="send"]`)).click();
        }, 1000);

        await new Promise(resolve => setTimeout(resolve, 2500));
    }
}

enviarScript().then(() => console.log("Mensagens enviadas")).catch(console.error);